# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: using-dynamic-content

frameworkVersion: '2'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x

# The `functions` block defines what code to deploy
functions:
  queryParamsExample:
    handler: handler.queryParamsExample
    # The `events` block defines how to trigger the handler.queryParamsExample code
    events:
      - http:
          path: hello
          method: get
  pathParamsExample:
    handler: handler.pathParamsExample
    events:
      - http:
          path: /
          method: get 
          cors: true
      - http:
          path: /{name}
          method: get
          cors: true